import { StyleSheet, Dimensions } from "react-native";

const { width } = Dimensions.get("window");
const CARD_WIDTH = (width - 56) / 2;

const feedStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#0D1118",
  },
  scrollView: {
    flex: 1,
  },
  detailOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "#0D1118",
    zIndex: 100,
  },
  header: {
    backgroundColor: "#0D1118",
    paddingTop: 20,
    paddingBottom: 16,
    paddingHorizontal: 20,
    borderBottomLeftRadius: 24,
    borderBottomRightRadius: 24,
  },
  headerContent: {
    gap: 12,
  },
  searchSection: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    width: "100%",
  },
  searchInputContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#1F2937",
    borderRadius: 16,
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderWidth: 1,
    borderColor: "#374151",
    flex: 1,
  },
  searchIcon: {
    marginRight: 13,
  },
  searchInput: {
    flex: 1,
    fontSize: 16,
    color: "#FFFFFF",
    padding: 0,
  },
  filterButton: {
    padding: 12,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#4C3BD7",
    backgroundColor: "#1F2937",
    position: "relative",
  },
  filterBadge: {
    position: "absolute",
    top: 5,
    right: 5,
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: "#EF4444",
  },
  activeFiltersContainer: {
    marginTop: 8,
  },
  activeFiltersContent: {
    paddingRight: 20,
    gap: 8,
    alignItems: "center",
  },
  activeFilterChip: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#4C3BD7",
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 20,
    gap: 6,
    marginRight: 8,
    borderWidth: 1,
    borderColor: "#4C3BD7",
  },
  activeFilterText: {
    fontSize: 12,
    fontWeight: "500",
    color: "#FFFFFF",
  },
  clearAllButton: {
    backgroundColor: "#EF4444",
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 20,
  },
  clearAllText: {
    fontSize: 12,
    fontWeight: "600",
    color: "#FFFFFF",
  },
  section: {
    backgroundColor: "#0D1118",
    marginTop: 8,
    paddingVertical: 16,
    paddingHorizontal: 16,
    marginHorizontal: 8,
    borderRadius: 16,
  },
  sectionHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 16,
  },
  sectionTitle: {
    fontSize: 25,
    fontWeight: "600",
    color: "#FFFFFF",
  },
  seeAll: {
    fontSize: 14,
    color: "#B072FF",
    fontWeight: "500",
    marginRight: 10,
  },
  productCount: {
    fontSize: 14,
    color: "#9CA3AF",
  },
  trendBrandsContainer: {
    flexGrow: 0,
  },
  trendBrandsContent: {
    paddingRight: 16,
    gap: 12,
  },
  trendBrandCard: {
    width: 120,
    borderRadius: 10,
    backgroundColor: "#1F2937",
    borderWidth: 1,
    borderColor: "#374151",
    overflow: "hidden",
  },
  trendBrandImage: {
    width: "100%",
    height: 80,
  },
  trendBrandInfo: {
    padding: 8,
  },
  trendBrandName: {
    color: "#FFFFFF",
    fontWeight: "600",
    fontSize: 12,
    marginBottom: 4,
  },
  trendBrandCount: {
    color: "#9CA3AF",
    fontSize: 10,
  },
  brandsContainer: {
    flexGrow: 0,
  },
  brandsContent: {
    flexDirection: "row",
    flexWrap: "nowrap",
  },
  brandChip: {
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "#374151",
    backgroundColor: "#1F2937",
    marginRight: 8,
    alignItems: "center",
    justifyContent: "center",
    minHeight: 40,
    minWidth: 80,
  },
  brandChipSelected: {
    backgroundColor: "#4C3BD7",
    borderColor: "#4C3BD7",
  },
  brandChipText: {
    color: "#E5E7EB",
    fontWeight: "500",
    fontSize: 14,
    textAlign: "center",
    includeFontPadding: false,
    textAlignVertical: "center",
  },
  brandChipTextSelected: {
    color: "#ffffff",
  },
  priceRangeContainer: {
    flexGrow: 0,
  },
  priceRangeContent: {
    paddingRight: 16,
  },
  priceChip: {
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderRadius: 20,
    backgroundColor: "#1F2937",
    marginRight: 8,
    borderWidth: 1,
    borderColor: "#374151",
    minWidth: 110,
  },
  priceChipSelected: {
    backgroundColor: "#4C3BD7",
    borderColor: "#4C3BD7",
  },
  priceChipText: {
    color: "#E5E7EB",
    fontWeight: "500",
    fontSize: 12,
    textAlign: "center",
  },
  priceChipTextSelected: {
    color: "#fff",
  },
  productsContainer: {
    paddingBottom: 24,
  },
  columnWrapper: {
    justifyContent: "space-between",
    gap: 16,
    marginBottom: 16,
    paddingRight: 4,
  },
  cardWrapper: {
    width: CARD_WIDTH,
  },
  productCard: {
    backgroundColor: "#1F2937",
    borderRadius: 12,
    overflow: "hidden",
    marginBottom: 16,
    borderWidth: 1,
    borderColor: "#374151",
  },
  imageContainer: {
    position: "relative",
    height: 150,
  },
  productImage: {
    width: "100%",
    height: "100%",
  },
  conditionBadge: {
    position: "absolute",
    top: 8,
    right: 8,
    backgroundColor: "rgba(0,0,0,0.7)",
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 4,
  },
  conditionText: {
    color: "#fff",
    fontSize: 12,
    fontWeight: "500",
  },
  productInfo: {
    padding: 12,
  },
  brandText: {
    fontSize: 14,
    fontWeight: "600",
    color: "#FFFFFF",
    marginBottom: 2,
  },
  modelText: {
    fontSize: 12,
    color: "#9CA3AF",
    marginBottom: 8,
  },
  requestAccessContainer: {
    marginBottom: 8,
    alignItems: "center",
  },
  requestAccessText: {
    width: 77,
    height: 15,
    color: "#B072FFCC",
    fontSize: 10,
    fontWeight: "500",
    fontFamily: "Inter",
    lineHeight: 15,
    textAlign: "center",
    verticalAlign: "middle",
    opacity: 1,
    marginBottom: 8,
  },
  watchStatusText: {
    color: "#9CA3AF",
    fontSize: 10,
    fontWeight: "500",
  },
  watchStatusButton: {
    width: 42,
    height: 20,
    backgroundColor: "#FFFFFF14",
    paddingTop: 2,
    paddingRight: 8,
    paddingBottom: 2,
    paddingLeft: 8,
    borderRadius: 9999,
    opacity: 1,
  },
  watchStatusButtonText: {
    color: "#FFFFFF",
    fontSize: 12,
    fontWeight: "600",
    textAlign: "center",
  },
  priceContainerCard: {
    marginBottom: 8,
  },
  priceTextCard: {
    fontSize: 16,
    fontWeight: "700",
    color: "#10B981",
  },
  metaContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  dateContainer: {
    flexDirection: "row",
    alignItems: "center",
  },
  dateText: {
    fontSize: 12,
    color: "#9CA3AF",
    marginLeft: 4,
  },
  viewsContainer: {
    flexDirection: "row",
    alignItems: "center",
  },
  viewsText: {
    fontSize: 12,
    color: "#9CA3AF",
    marginLeft: 4,
  },
  emptyContainer: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 48,
  },
  emptyText: {
    fontSize: 16,
    color: "#9CA3AF",
    marginTop: 16,
    marginBottom: 24,
  },
  resetButton: {
    alignSelf: "center",
  },
  // Modal Styles
  modalContainer: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.8)",
    justifyContent: "flex-end",
  },
  modalContent: {
    backgroundColor: "#0D1118",
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    maxHeight: "85%",
    borderWidth: 1,
    borderColor: "#374151",
  },
  modalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: "#374151",
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: "600",
    color: "#FFFFFF",
  },
  closeButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: "#374151",
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#6B7280",
  },
  modalScrollView: {
    paddingHorizontal: 20,
    paddingVertical: 16,
  },
  filterSection: {
    marginBottom: 24,
  },
  filterSectionTitle: {
    fontSize: 18,
    fontWeight: "600",
    color: "#FFFFFF",
    marginBottom: 12,
  },
  modalSearchInputContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#1F2937",
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderWidth: 1,
    borderColor: "#374151",
    marginBottom: 16,
  },
  modalSearchInput: {
    flex: 1,
    fontSize: 16,
    color: "#FFFFFF",
    padding: 0,
  },
  brandContainer: {
    width: 390,
    opacity: 1,
    flexDirection: "row",
    flexWrap: "wrap",
    alignContent: "flex-start",
    justifyContent: "space-between",
    rowGap: 12,
    columnGap: 12,
    marginBottom: 16,
  },
  brandButton: {
    width: 118,
    height: 38,
    backgroundColor: "#1F2937",
    borderRadius: 9999,
    paddingTop: 8,
    paddingRight: 12,
    paddingBottom: 8,
    paddingLeft: 12,
    borderWidth: 1,
    borderColor: "#374151",
    alignItems: "center",
    justifyContent: "center",
    opacity: 1,
  },
  brandButtonSelected: {
    backgroundColor: "#4C3BD7",
    borderColor: "#4C3BD7",
  },
  brandButtonText: {
    fontSize: 14,
    fontWeight: "500",
    color: "#9CA3AF",
  },
  brandButtonTextSelected: {
    color: "#FFFFFF",
  },
  featuredBrandsRow: {
    flexDirection: "row",
    gap: 8,
    marginBottom: 8,
  },
  featuredBrandChip: {
    flex: 1,
    backgroundColor: "#1F2937",
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "#374151",
    alignItems: "center",
  },
  featuredBrandChipSelected: {
    backgroundColor: "#4C3BD7",
    borderColor: "#4C3BD7",
  },
  featuredBrandText: {
    fontSize: 14,
    fontWeight: "500",
    color: "#9CA3AF",
  },
  featuredBrandTextSelected: {
    color: "#FFFFFF",
  },
  sliderContainer: {
    marginBottom: 16,
  },
  sliderLabel: {
    fontSize: 16,
    fontWeight: "500",
    color: "#FFFFFF",
    marginBottom: 12,
  },
  modernSliderContainer: {
    position: "relative",
    height: 40,
    justifyContent: "center",
  },
  modernSliderTrack: {
    height: 4,
    backgroundColor: "#374151",
    borderRadius: 2,
    position: "relative",
  },
  modernSliderProgress: {
    position: "absolute",
    height: "100%",
    backgroundColor: "#4C3BD7",
    borderRadius: 2,
  },
  modernSliderThumb: {
    position: "absolute",
    width: 20,
    height: 20,
    backgroundColor: "#4C3BD7",
    borderRadius: 10,
    justifyContent: "center",
    alignItems: "center",
    top: -8,
  },
  modernSliderThumbInner: {
    width: 8,
    height: 8,
    backgroundColor: "#FFFFFF",
    borderRadius: 4,
  },
  sliderTouchableArea: {
    position: "absolute",
    top: -10,
    left: 0,
    right: 0,
    bottom: -10,
  },
  priceInputsContainer: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  priceInputWrapper: {
    flex: 1,
  },
  priceInputLabel: {
    fontSize: 14,
    fontWeight: "500",
    color: "#9CA3AF",
    marginBottom: 8,
  },
  modernPriceInput: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#1F2937",
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderWidth: 1,
    borderColor: "#374151",
  },
  currencySymbol: {
    fontSize: 16,
    color: "#9CA3AF",
    marginRight: 8,
  },
  modernPriceInputText: {
    flex: 1,
    fontSize: 16,
    color: "#FFFFFF",
    padding: 0,
  },
  priceInputDivider: {
    alignItems: "center",
    justifyContent: "center",
    width: 20,
  },
  priceDividerText: {
    fontSize: 16,
    color: "#9CA3AF",
  },
  conditionChipsRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  conditionChip: {
    backgroundColor: "#1F2937",
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "#374151",
  },
  conditionChipSelected: {
    backgroundColor: "#6366F1",
    borderColor: "#6366F1",
  },
  conditionChipText: {
    fontSize: 14,
    fontWeight: "500",
    color: "#9CA3AF",
  },
  conditionChipTextSelected: {
    color: "#FFFFFF",
  },
  locationDropdown: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    backgroundColor: "#1F2937",
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderWidth: 1,
    borderColor: "#374151",
  },
  locationDropdownText: {
    fontSize: 16,
    color: "#FFFFFF",
  },
  locationDropdownList: {
    backgroundColor: "#1F2937",
    borderRadius: 12,
    marginTop: 8,
    borderWidth: 1,
    borderColor: "#374151",
    overflow: "hidden",
  },
  locationDropdownItem: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#374151",
  },
  locationDropdownItemSelected: {
    backgroundColor: "#6366F1",
  },
  locationDropdownItemText: {
    fontSize: 16,
    color: "#FFFFFF",
  },
  locationDropdownItemTextSelected: {
    color: "#FFFFFF",
  },
  modalFooter: {
    flexDirection: "row",
    gap: 12,
    paddingHorizontal: 20,
    paddingVertical: 16,
    borderTopWidth: 1,
    borderTopColor: "#374151",
  },
  modalButton: {
    flex: 1,
    marginHorizontal: 4,
  },
});

export { CARD_WIDTH };
export default feedStyles;
