import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  modalContainer: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.8)",
    justifyContent: "flex-end",
  },
  modalContent: {
    backgroundColor: "#0D1118",
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    maxHeight: "85%",
    borderWidth: 1,
    borderColor: "#374151",
  },
  modalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    padding: 20,
    borderBottomWidth: 1,
    borderBottomColor: "#374151",
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: "bold",
    color: "#FFFFFF",
  },
  modalScrollView: {
    maxHeight: 500,
    paddingHorizontal: 16,
  },
  modalFooter: {
    flexDirection: "row",
    justifyContent: "space-between",
    padding: 20,
    borderTopWidth: 1,
    borderTopColor: "#374151",
    gap: 12,
  },
  modalButton: {
    flex: 1,
    paddingVertical: 12,
    borderRadius: 8,
    alignItems: "center",
  },
  resetButton: {
    backgroundColor: "#1F2937",
    borderWidth: 1,
    borderColor: "#374151",
  },
  applyButton: {
    backgroundColor: "#B072FF",
  },
  resetButtonText: {
    color: "#E5E7EB",
    fontSize: 14,
    fontWeight: "500",
  },
  applyButtonText: {
    color: "#FFFFFF",
    fontSize: 14,
    fontWeight: "500",
  },
  filterSection: {
    marginBottom: 24,
  },
  filterSectionTitle: {
    fontSize: 16,
    fontWeight: "600",
    marginTop: 20,
    paddingBottom: 12,
    color: "gray",
  },
  modalSearchInputContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#1F2937",
    borderRadius: 8,
    paddingHorizontal: 12,
    height: 40,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: "#374151",
  },
  searchIcon: {
    marginRight: 8,
  },
  modalSearchInput: {
    flex: 1,
    fontSize: 14,
    color: "#FFFFFF",
  },
  featuredBrandsRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 12,
    gap: 8,
  },
  featuredBrandChip: {
    flex: 1,
    backgroundColor: "#1F2937",
    borderRadius: 20,
    paddingVertical: 8,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "#374151",
    minHeight: 40,
  },
  featuredBrandChipSelected: {
    backgroundColor: "#6366F1",
    borderColor: "#6366F1",
  },
  featuredBrandText: {
    fontSize: 14,
    color: "#E5E7EB",
    fontWeight: "500",
    textAlign: "center",
  },
  featuredBrandTextSelected: {
    color: "#FFFFFF",
  },
  priceRangeDisplay: {
    alignItems: "center",
    marginBottom: 16,
  },
  priceRangeText: {
    fontSize: 16,
    fontWeight: "500",
    color: "#FFFFFF",
  },
  sliderContainer: {
    marginBottom: 20,
  },
  modernSliderContainer: {
    height: 40,
    justifyContent: "center",
    marginVertical: 16,
  },
  modernSliderTrack: {
    height: 4,
    backgroundColor: "#E5E7EB",
    borderRadius: 2,
    position: "relative",
  },
  modernSliderProgress: {
    height: 4,
    backgroundColor: "#6366F1",
    borderRadius: 2,
    position: "absolute",
  },
  modernSliderThumb: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: "#fff",
    borderWidth: 2,
    borderColor: "#6366F1",
    position: "absolute",
    justifyContent: "center",
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
    elevation: 2,
  },
  modernSliderThumbInner: {
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: "#6366F1",
  },
  sliderTouchableArea: {
    position: "absolute",
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
    backgroundColor: "transparent",
  },
  priceInputsContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
  },
  priceInputWrapper: {
    width: "48%",
  },
  priceInputLabel: {
    fontSize: 12,
    color: "#6B7280",
    marginBottom: 4,
  },
  modernPriceInput: {
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#D1D5DB",
    borderRadius: 8,
    paddingHorizontal: 12,
    height: 44,
    backgroundColor: "#fff",
  },
  currencySymbol: {
    fontSize: 16,
    color: "#9CA3AF",
    marginRight: 4,
  },
  modernPriceInputText: {
    flex: 1,
    fontSize: 16,
    color: "#111827",
  },
  conditionChipsRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  conditionChip: {
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "#374151",
    backgroundColor: "#1F2937",
  },
  conditionChipSelected: {
    borderColor: "#6366F1",
    backgroundColor: "#6366F1",
  },
  conditionChipText: {
    fontSize: 14,
    color: "#E5E7EB",
    fontWeight: "500",
  },
  conditionChipTextSelected: {
    color: "#FFFFFF",
  },
  locationDropdown: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    borderWidth: 1,
    borderColor: "#D1D5DB",
    borderRadius: 8,
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: "#fff",
  },
  locationDropdownText: {
    fontSize: 16,
    color: "#111827",
  },
  locationDropdownList: {
    marginTop: 8,
    borderWidth: 1,
    borderColor: "#E5E7EB",
    borderRadius: 8,
    backgroundColor: "#fff",
    overflow: "hidden",
  },
  locationDropdownItem: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#F3F4F6",
  },
  locationDropdownItemSelected: {
    backgroundColor: "#F5F3FF",
  },
  locationDropdownItemText: {
    fontSize: 16,
    color: "#374151",
  },
  locationDropdownItemTextSelected: {
    color: "#6366F1",
    fontWeight: "500",
  },
});

export default styles;
