import { StyleSheet, Dimensions, ImageStyle } from "react-native";

const { width } = Dimensions.get("window");

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#000000",
  },
  loadingText: {
    color: "#FFFFFF",
    textAlign: "center",
    marginTop: 100,
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    paddingBottom: 20,
  },
  header: {
    paddingHorizontal: 20,
    paddingTop: 50,
    paddingBottom: 20,
  },
  backButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: "rgba(0, 0, 0, 0.7)",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.2)",
  },
  profileSection: {
    flexDirection: "row",
    paddingHorizontal: 20,
    marginBottom: 24,
  },
  profileImageContainer: {
    position: "relative",
    marginRight: 16,
  },
  profileImage: {
    width: 72,
    height: 72,
    borderRadius: 9999,
    borderWidth: 2,
    borderColor: "#FFFFFF",
  } as ImageStyle,
  verifiedBadge: {
    position: "absolute",
    bottom: -2,
    right: -2,
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: "#FFD700",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 2,
    borderColor: "#000000",
  },
  profileInfo: {
    flex: 1,
    justifyContent: "center",
  },
  nameContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 8,
    width: 240.328125,
    height: 28,
    gap: 8,
  },
  sellerName: {
    fontSize: 20,
    fontWeight: "700",
    color: "#FFFFFF",
  },
  verifiedTag: {
    width: 60,
    height: 22,
    borderRadius: 9999,
    borderWidth: 1,
    borderColor: "#FFFFFF",
    borderTopWidth: 1,
    borderTopColor: "#CBB891",
    paddingTop: 2,
    paddingRight: 6,
    paddingBottom: 2,
    paddingLeft: 6,
    alignItems: "center",
    justifyContent: "center",
  },
  verifiedTagText: {
    fontSize: 12,
    fontWeight: "500",
    color: "#FFFFFF",
  },
  location: {
    fontFamily: "Inter",
    fontWeight: "400",
    fontStyle: "normal",
    fontSize: 14,
    lineHeight: 20,
    color: "#9CA3AF",
    textAlignVertical: "center",
  },
  statsScrollView: {
    marginBottom: 32,
  },
  statsContainer: {
    flexDirection: "row",
    paddingHorizontal: 20,
    gap: 4,
  },
  statItem: {
    width: 99.109375,
    height: 38,
    borderRadius: 9999,
    borderWidth: 1,
    borderColor: "#FFFFFF14",
    paddingTop: 9,
    paddingRight: 13,
    paddingBottom: 9,
    paddingLeft: 13,
    backgroundColor: "#141821",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
  },
  singleStar: {
    width: 13.125208854675293,
    height: 12.251733779907227,
    marginTop: 0.87,
    marginLeft: 2,
  },
  ratingValue: {
    fontSize: 12,
    fontWeight: "600",
    color: "#FFFFFF",
    marginLeft: 2,
    textAlign: "center",
  },
  reviewsValue: {
    fontSize: 10,
    fontWeight: "400",
    color: "#FFFFFF",
    marginLeft: 1,
    textAlign: "center",
  },
  memberStatItem: {
    width: 155.859375,
    height: 38,
    borderRadius: 9999,
    borderWidth: 1,
    borderColor: "#FFFFFF14",
    paddingTop: 9,
    paddingRight: 13,
    paddingBottom: 9,
    paddingLeft: 13,
    backgroundColor: "#141821",
    alignItems: "center",
    justifyContent: "center",
  },
  starsContainer: {
    flexDirection: "row",
    marginBottom: 8,
  },
  starIcon: {
    marginRight: 2,
  },
  statValue: {
    width: 130,
    height: 20,
    fontFamily: "Inter",
    fontWeight: "400",
    fontStyle: "normal",
    fontSize: 14,
    lineHeight: 20,
    color: "#FFFFFF",
    textAlign: "center",
    textAlignVertical: "center",
  },
  tradesValue: {
    width: 74,
    height: 20,
    fontFamily: "Inter",
    fontWeight: "400",
    fontStyle: "normal",
    fontSize: 14,
    lineHeight: 20,
    color: "#FFFFFF",
    textAlign: "center",
    textAlignVertical: "center",
  },
  tradesButton: {
    width: 99.109375,
    height: 38,
    borderRadius: 99,
    borderWidth: 1,
    borderColor: "#FFFFFF14",
    backgroundColor: "#141821",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 0,
  },
  tradesLabel: {
    width: 74,
    height: 20,
    fontFamily: "Inter",
    fontWeight: "400",
    fontStyle: "normal",
    fontSize: 14,
    lineHeight: 20,
    color: "#9CA3AF",
    textAlign: "center",
    textAlignVertical: "center",
  },
  tradesNumber: {
    width: 74,
    height: 20,
    fontFamily: "Inter",
    fontWeight: "400",
    fontStyle: "normal",
    fontSize: 14,
    lineHeight: 20,
    color: "#FFFFFF",
    textAlign: "center",
    textAlignVertical: "center",
  },
  memberButton: {
    width: 155.859375,
    height: 38,
    borderRadius: 9999,
    borderWidth: 1,
    borderColor: "#FFFFFF14",
    paddingTop: 9,
    paddingRight: 13,
    paddingBottom: 9,
    paddingLeft: 13,
    backgroundColor: "#141821",
    alignItems: "center",
    justifyContent: "center",
  },
  memberLabel: {
    width: 130,
    height: 20,
    fontFamily: "Inter",
    fontWeight: "400",
    fontStyle: "normal",
    fontSize: 14,
    lineHeight: 20,
    color: "#9CA3AF",
    textAlign: "center",
    textAlignVertical: "center",
  },
  memberYear: {
    fontSize: 12,
    fontWeight: "600",
    color: "#FFFFFF",
    textAlign: "center",
  },
  ratingStatItem: {
    width: 102.6875,
    height: 38,
    borderRadius: 9999,
    borderWidth: 1,
    borderColor: "#FFFFFF14",
    paddingTop: 9,
    paddingRight: 13,
    paddingBottom: 9,
    paddingLeft: 13,
    backgroundColor: "#141821",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 4,
  },

  aboutSection: {
    width: 398,
    height: 170,
    backgroundColor: "#141821",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#FFFFFF14",
    borderTopWidth: 1,
    borderTopColor: "#FFFFFF14",
    marginHorizontal: 16,
    marginTop: 20,
    marginBottom: 24,
    padding: 16,
    alignSelf: "center",
  },
  sectionTitle: {
    width: 48,
    height: 24,
    fontFamily: "Inter",
    fontWeight: "600",
    fontStyle: "normal",
    fontSize: 16,
    lineHeight: 24,
    color: "#FFFFFF",
    textAlignVertical: "center",
    marginBottom: 12,
  },
  aboutText: {
    width: 364.3125,
    height: 60,
    fontFamily: "Inter",
    fontWeight: "400",
    fontStyle: "normal",
    fontSize: 14,
    lineHeight: 20,
    color: "#9CA3AF",
    textAlignVertical: "center",
    marginBottom: 8,
  },
  credentialsContainer: {
    flexDirection: "row",
    gap: 6,
    marginTop: 2,
  },
  credentialItem: {
    width: 172.078125,
    height: 28,
    borderRadius: 9999,
    paddingTop: 6,
    paddingRight: 12,
    paddingBottom: 6,
    paddingLeft: 12,
    backgroundColor: "rgba(76, 59, 215, 0.15)",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
  },
  credentialText: {
    fontSize: 12,
    color: "#FFFFFF",
    marginLeft: 6,
    fontWeight: "500",
  },
  actionButtons: {
    flexDirection: "row",
    paddingHorizontal: 20,
    marginBottom: 32,
    gap: 12,
    justifyContent: "space-between",
  },
  messageButton: {
    width: 180,
    height: 46,
    borderRadius: 8,
    paddingTop: 12,
    paddingBottom: 12,
    backgroundColor: "#4C3BD7",
    alignItems: "center",
    justifyContent: "center",
  },
  messageButtonText: {
    color: "#FFFFFF",
    fontWeight: "600",
    fontSize: 16,
  },
  followButton: {
    width: 192,
    height: 46,
    borderRadius: 8,
    paddingTop: 12,
    paddingBottom: 12,
    backgroundColor: "transparent",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "#FFFFFF",
  },
  followButtonText: {
    color: "#FFFFFF",
    fontWeight: "600",
    fontSize: 16,
  },
  inventorySection: {
    paddingHorizontal: 20,
    marginBottom: 20,
  },
  inventoryGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
    gap: 12,
  },
  inventoryItem: {
    width: (width - 52) / 2,
    backgroundColor: "#1F2937",
    borderRadius: 12,
    marginBottom: 16,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "#374151",
  },
  inventoryImage: {
    width: "100%",
    height: 140,
  } as ImageStyle,
  inventoryInfo: {
    padding: 16,
  },
  inventoryBrand: {
    width: 117,
    height: 20,
    fontFamily: "Inter",
    fontWeight: "600",
    fontStyle: "normal",
    fontSize: 14,
    lineHeight: 20,
    color: "#FFFFFF",
    textAlignVertical: "center",
    marginBottom: 4,
  },
  inventoryModel: {
    width: 165,
    height: 16,
    fontSize: 14,
    color: "#9CA3AF",
    marginTop: 8,
    marginBottom: 12,
  },
  inventoryActions: {
    marginBottom: 12,
  },
  requestAccessText: {
    width: 165,
    height: 15,
    fontSize: 12,
    color: "#8B5CF6",
    fontWeight: "500",
    textAlign: "left",
  },
  inventoryMeta: {
    flexDirection: "row",
    justifyContent: "flex-start",
    alignItems: "center",
    marginBottom: 8,
  },
  bottomRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  conditionBadge: {
    height: 20,
    backgroundColor: "#374151",
    borderRadius: 9999,
    paddingTop: 2,
    paddingRight: 8,
    paddingBottom: 2,
    paddingLeft: 8,
    marginTop: 4,
    alignItems: "center",
    justifyContent: "center",
    minWidth: 26,
  },
  conditionText: {
    height: 16,
    fontFamily: "Inter",
    fontWeight: "400",
    fontStyle: "normal",
    fontSize: 12,
    lineHeight: 16,
    color: "#FFFFFF",
    textAlignVertical: "center",
    textAlign: "center",
  },
  viewsContainer: {
    width: 39.859375,
    height: 16,
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    marginTop: 4,
  },
  viewsText: {
    fontSize: 12,
    color: "#9CA3AF",
  },
  addedText: {
    fontSize: 12,
    color: "#9CA3AF",
  },
  bottomSpacing: {
    height: 20,
  },
  aboutTitle: {
    width: 48,
    height: 24,
    fontFamily: "Inter",
    fontWeight: "600",
    fontStyle: "normal",
    fontSize: 16,
    lineHeight: 24,
    color: "#FFFFFF",
    textAlignVertical: "center",
    marginBottom: 8,
  },
  authorText: {
    fontSize: 14,
    fontWeight: "500",
    color: "#8B5CF6",
    marginBottom: 8,
  },
  inventoryTitle: {
    fontSize: 20,
    fontWeight: "700",
    color: "#FFFFFF",
    marginBottom: 16,
  },
  statLabel: {
    width: 74,
    height: 20,
    fontFamily: "Inter",
    fontWeight: "400",
    fontStyle: "normal",
    fontSize: 14,
    lineHeight: 20,
    color: "#9CA3AF",
    textAlign: "center",
    textAlignVertical: "center",
  },
});

export default styles;
